### PR TITLE
add @gh1dra

### PR DESCRIPTION
**Pull request by corydickson**
Let me know if there is anything else I need to provide!
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I'm @gh1dra on Keybase and I am validating myself as @gh1dra on aragon.forum.org
-----BEGIN PGP SIGNATURE-----

wsFcBAEBCAAQBQJcywN8CRAcQYWgRHchZQAAgk0QAF1rDucTsHKPniwMMW1z1ubS
NF5UCLziDpLfKFnT0xc6Kjsq+Yc4+91oKxurndZjvh2E+qRKUJVtBYtDNH7Lj8p6
QPh99PEMKHhxRPc83Ho3jJNHj/BPoiaD3ANr/FIppJKjrr1ZPPOv4T8iiQkV36Ft
SADnkbQLbYVz2YqaBlOa8BIbQ8SP8bOBX32akK0NfhM7e1Hlmtvi4dHrok358xP7
vW3C2Az+cRyHW3+czveW3BoDZBGBpec67Pyq2h3LOJg1HWgRJ2jmNVPwcEzJzDXp
2VvnOiXyjZg5f6iDe5sWEzBukYBcSmWBNJiqXw9EP7b9xzV8To3yyZB2/lsJp/MB
jYd8eYS1sog3P3BTRT837R87m/OxRx696EyiSX3iuyWf3gg8SE7ZTHEK4DS0yDRP
2lqEee+4KW1pZ/AbAWQp2fByRpsaWVCqdasAhnGur4dywrUi4ax9z7nG1WPCmh7U
R7NUxRbjrVIfIu+ua5vaQKp7PWcH5R3tZtGQQtWoV6AR6P1yRQrprneH7dNc8Vt+
xnQVBzY4liTFJai6gW39aOdqP2Jbnl3/jwSeXPY+hDUdxp1cRNfxjkr0sYuQHxhn
RCpIIBY1COZqvQwLi6qFjH10GZSkoLWjiYmSPYi2ekwT10stEOrp4u8PN0tMTskR
bqymG2D1Ky5E8kaR7DRQ
=5YCZ
-----END PGP SIGNATURE-----
```

### CODE REVIEW

**Review by bingen — APPROVED** [review]

**Comment by lkngtn** [comment]
@sepu85 @julianbrooks 

Im not really sure what to do with membership requests at this point, please advise. :)

**Comment by julianbrooks** [comment]
> @sepu85 @julianbrooks
> 
> Im not really sure what to do with membership requests at this point, please advise. :)

I think whoever is part of our community and has fulfilled the keybase process has to be in. For me seems unfair to shut the gate with people half in. 

Happy to go with majority view but that seems 'fair' at this point. @sepu85, any thoughts?

**Comment by julianbrooks** [comment]
I think too we're going to have to have some kind of virtual validation of members
(perhaps recorded coop meeting with everyone on camera briefly or somesuch (cc @jjperezaguinaga )

**Comment by julianbrooks** [comment]
Last thing -  @lkngtn, could Gus and I become reviewers please?

**Comment by sepu85** [comment]
> I think whoever is part of our community and has fulfilled the keybase process has to be in. For me seems unfair to shut the gate with people half in.

I disagree, we should be more strict in the process, but not too complicated... maybe asking a referral (and tracing it on Github oc) from an AragonCoop Merit token holder could work...

**Comment by sepu85** [comment]
Adding on top of my previous comment...

I have gave more thoughts on this, and the referral process might not be optimal neither as it risks cartel creation...

The community haven't pronnounced either about this... So we need to give more thoughts yet.

For the momment, I'm happy to include the people that has pronnounced their willing to participate as long we don't have flood in our Membership request and/or not recogniced (unknow) people willing to be part of this...

**Review by lkngtn — COMMENTED** [review]
I'm no longer managing this and just trying to remove the PR review request.

**Pull request closed without merging**
