### PR TITLE
adding me :-) gustavosegovia

### PR DESCRIPTION
**Pull request by sepu85**

### CODE REVIEW

**Review by lkngtn — APPROVED** [review]
Sorry for the delayed response! Let's get you in there!

**Comment by lkngtn** [comment]
@bingen @jjperezaguinaga @stellarmagnet Please help! :)

**Review by bingen — APPROVED** [review]
Yes, sorry for the late response too!

**Comment by lkngtn** [comment]
@sepu85 Going to go ahead and add a token for you, but before we merge can provide a keybase proof (like https://github.com/aragoncoop/membership/pull/10) as a comment on this PR?

**Comment by sepu85** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I am @sepu85 (in the Aragon Forum)  and my ethereum address is 0x6543c99d0e073c140Fd08A741c6cfdcd1449da94
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.1.0
Comment: https://keybase.io/crypto

wsFcBAABCgAGBQJcpN78AAoJEHrp82pU04t1rg0P/RVJSuKcJfL/xBox44j2HKXK
SH2/rja63w8Vu4jrpfjl94b7nQoH2ZoO/AaK4Oc5BcE+h0a0DAtFPauCqhQyjEZ9
+CIZKMrIGwc/bHAsrO8zdPFLDeeb8IPvkQ4pphNlNcrnk19rzEFyuOQCzygpU31Y
I24bidbDDO7a70jX8GPUkZgaysUv4ntZpmyxw+zvrv8zBHH8bqu9+KHDJ2J/12E9
LliQLJrlixb5JiKix5Xkph9Y8DqZ8dgmMuC7p2nHpqgoIk1wIMmOfV+crLhU3qPk
MokJytcVWIwGwDv6PH6pZASUqUmm7nA5uCkEhmVFWwgN9SK8zkAdVWcHBUNLRXuI
gxPi7Mfvem/+rTFhhVgZ/2pVW0nhh53OcIsWuC1b1Hlgy5C/SelHcN3NbbpI3HKL
SPxx8maJQpagdbf/iz3vyf0iZh+142r3byU3YJd0tSyZEgmh/c5ulzTx6zPAWN16
k4Fnyyclk0uGvEJxKbbqWNRXouimz9/uL8Kfviv8MFJcFy503wQMWPmUuV88vYXL
VWwgYitzb7fqYPP6zGQj6/uBUhVpDDZhKdTNlmnvFmCCrhzx47lNV+l72saMnCGK
jObpZed2ljaJXS2K8Wcb+O8NJlWt8tjjlP3WtewUagFCmJyHcW4Y0iG4If1PDJ4Z
Bza4xlanH3+68ZnezDW0
=RVZl
-----END PGP SIGNATURE-----

**Comment by sepu85** [comment]
done @lkngtn

**Pull request merged**
