### PR TITLE
Update member_registry.md with @osarrouy address

### PR DESCRIPTION
**Pull request by osarrouy**
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I am @osarrouy on keybase and my Ethereum address is 0x8873b045d40A458e46E356a96279aE1820a898bA
-----BEGIN PGP SIGNATURE-----

wsFcBAEBCAAQBQJcSJjnCRCx9g9XUidNwwAAEsYQAH+2O85dtPFrKWkfoQ8AI43g
r6OTWHeYLy2N44a+udVjBgxwtui+eGCRWIMrPDGYHaAPeLUWO79Xe5lYoysjWos6
TM7TPOxf/S9izjHGZB7+jxgV/adSOUv86uKYN+MhKS8tk2Qu38S8HkmYmee1AUfR
MDlSAX17iVGndwakYK+ZDzUjNqefUeBVTIfVB+Zxg2QGjT3eRs6zUU8NRdiIg+1x
on3EFoDFxUXEkgGJSRMNq2VVfIJXL8raX9Dx8vpFsDtD8iAyHsfZJ3/20EuZt7iD
4xQuIPdqz2dAxR8gt9Oyqo59WOsdCZ9Qe++Kij0s4r12Q2b6VzOjxfnkbJ26v9Qu
DNLOkhQgccNFDt0vX6hBCqPJNvNQYBHULwOqeG14aVfQ5Tht6v5spbcKojR3u1BO
Bk9Nh9BMrZLp8q+bOILAMxu25nUGqypLKTLHa57dEE/c8DZAm80XkgXpkbnzjxZL
LltIJbj69XpuHDz2ovwygXUg2Gva06HRahN9d76ugeIQfDjhtwfiSS8lysaVRoca
VBXuX2J0geStlhBe29gWBj8RTxDhqAR7fKc8Xr3dVD2u5iBU9eCC8HZi+bJgCRVi
0gnUp3XQLBC9EVORfBqZYtE6wGLF0HVwnxnc+H+Yd5TBWV6LNXb36TbQaXqwXFnY
RgbnlZEOrwsb99Xf2S20
=wa3b
-----END PGP SIGNATURE-----

### CODE REVIEW

**Review by bingen — APPROVED** [review]
I think you were supposed to put a keybase signed message in the comments section (@lkngtn can confirm), otherwise looks good to me

**Comment by lkngtn** [comment]
Yup please do include a signed message saying your keybase username and address in the PR comments. 

We should update the readme to reflect the PR process. :)

**Comment by osarrouy** [comment]
Done. Hope it's all good :)

**Review by 0xjjpa — APPROVED** [review]
✅

**Pull request merged**
