### PR TITLE
Update member_registry.md

### PR DESCRIPTION
**Pull request by rkzel**
Thank you!

### CODE REVIEW

**Comment by lkngtn** [comment]
Please comment here with a signed keybase message, saying your keybase username and the eth address. :)

**Review by lkngtn — APPROVED** [review]
This looks correct. Thanks @jjperezaguinaga for updating to reflect the recent changes.

**Comment by julianbrooks** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I'm @julian_brooks on Keybase and my Ethereum address is: 0x505559E39993cAC587560368BDC04D93c62b35b1
-----BEGIN PGP SIGNATURE-----

wsFcBAEBCAAQBQJcSNfJCRDTv0DzugTvKAAACmQQADBApMV2S2tcf1X83y9B2Ju+
Uvwzm4u0vJODx1gQeo5MRypnwZJis9JfiEPtGdJnHosIuKnEK85c13xg9tOdc+D/
ZpEsjDg0wgNkT1MFw44ETrAgIjSl+raPhiPhOlvoWHy97/3v92nb3YIyGvNy8QtK
YEbf9wu9AivofjwtGqZKJZQDoUBHR4lw33OEdzwDZLAl/0eH8q8t6JSNiGKjWD42
P9WMLSBZaFIbFRYfYgRneA0qijvEeYphACBYugEnn8JlM/0JSkxcEz7rTrP0i6gy
Vvs///le22aEJVH9hqMCLLujXX7IzkknZb+IO3cNQDbNidVAZ3VEHhbI87QuAYN7
FdcSmBHxpHUhfvAo2gHB7nIylh8UI2+CTUTiD8E+xhoo8dbWZc4gg1s1TiCqBVoK
HC80SVPPVKShHPaIk5f7xuXkzQWKcf/Oeww9O2LdxMhx3Gt7vKUDpFINCkFai1G0
QK0DzMS3+zRLIDMeP7cgA5ioafSpA9m2gU+K1EGonijhjU417HnkA1hWO5O/jV7f
vFgmNRZUmetO47G2beI5uIMK2laZpSE9nS3A4Afd5FyE5I9/vTF1uUG42oIYOk4C
CnjBBSHFmjia17UC+GNIq9G8gkviYbb0O3qJ/+vmQHmsQeUX/r/M1AW/qTsbHvF2
EDk1YvjBHCYoEMNwpQrR
=feNd
-----END PGP SIGNATURE-----
```

**Comment by bingen** [comment]
@julianbrooks shouldn't you use your own PR?

**Review by 0xjjpa — CHANGES_REQUESTED** [review]
Missing the signature in the comment 👀

**Comment by rkzel** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi, I’m @rkzel on Keybase and my Eth address is 0x66C2211376dF03E34a7E2820125d16b6994c76AD
-----BEGIN PGP SIGNATURE-----

iQHJBAEBCgAzFiEEEfGx5vxZ43PW0vGCM5jpeLgaK0EFAlxJsbwVHHJremVsQGh5
cGVybG9nb3MubmV0AAoJEDOY6Xi4GitB2kUL/i7kgyNs4ZbdJl0CiGaS/CBd3zWh
8g2nNSnHRPh14LYoKQKVpnec5MHxcPVJJsU7x6Fb1POCcaNQQyqzRc+8wivg91TF
0clC96W86JD1XvLlz8Lf1fTwI/DM+6FiSjLRtbfZHBu3KlgmEiO0t+v0hggYM+uh
SxkID6TsZDdwKG1YQ5ESKS8szPHyA3HnECS0gghz+U6lz2WnEFJah/UFHjJcBcnj
9hfKmdvkmBHrHBMCWWSZOIZ7NRjZMX4/nmE+AlaZUMIDPkd7g8KDxOHSsVPkIktU
ziFjG7GtBBqT1qsYGlxRw07fuog7uIaYqb8td9tdAnPBAeurdLgFpg7GGoQ+DATe
U0S3IX6vZ8h6lJWlxi6CQV9oEDjoLubCVfJ9cAeqiOja3e5cRh2SWZrytRiUDOzE
cT+V/o1WB8pZJfHLIs0fzubJ97YFC/Rh9F8AtjVzcjdG0DNieOrJR9+S8Dd5Fou1
NTkyq1mWnLR1BiorLN/moKGtNPFeQf9vfyfrGQ==
=bDeT
-----END PGP SIGNATURE-----

```

**Review by 0xjjpa — APPROVED** [review]

**Comment by 0xjjpa** [comment]
image
Good stuff!

**Pull request merged**
