### PR TITLE
Change the filename to README

### PR DESCRIPTION
**Pull request by stellarmagnet**
how about we rename the file readme, so it automatically displays when the repo is accessed?

### CODE REVIEW

**Comment by lkngtn** [comment]
I was thinking we should use the readme to provides some information on how to use the repo/file.

**Comment by 0xjjpa** [comment]
I'm with @stellarmagnet since the README is automatically parsed by GitHub and the first thing we see when we land to the repo.

**Review by 0xjjpa — APPROVED** [review]
✅

**Comment by lkngtn** [comment]
If we do that, will people know they need to submit a PR with a keybase signature? 

I know I put that in keybase and thats how people know to do it now, but there isn't a way to pin that in keybase so it sort of feels like it should be in the readme. 

We could have some documentation at the top of the file and then table though?

**Comment by 0xjjpa** [comment]
@lkngtn As a side note, I remembered that Keybase has a public registry where you can record your own and teams information. For instance, I have my address in [Keybase](https://keybase.pub/jjperezaguinaga/aragon_membership.txt) related to my Aragon Cooperative membership, so anyone can check it there. We can store those in a team folder as well.

In a more related note, we can put all instructions in the README, and describe that "approval" for membership needs to be done through updating this PR or using a CONTRIBUTORS file. I think we are still pretty open to options.

**Comment by 0xjjpa** [comment]
I'm on favour of moving this forward, thoughts @lkngtn ?

**Review by lkngtn — APPROVED** [review]
Okay, lets go ahead and move this to readme. We can always update it with better documentation later.

**Comment by bingen** [comment]
Too late, but this looks good to me.

**Pull request merged**
